name: publish

on:
  release:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: corepack enable
      # - run: npm i -g npm@latest
      - run: pnpm install --frozen-lockfile

      - run: pnpm run lint
      - run: pnpm run test
      - run: pnpm run build

      - name: Debug npm publish context
        run: |
          node -v
          npm -v
          echo "registry=$(npm config get registry)"
          NAME=$(node -p "require('./packages/text-vide/package.json').name")
          echo "pkg.name=${NAME}"
          npm view "${NAME}" name maintainers || true
          cat ./packages/text-vide/package.json

      - run: |
          cp ./README.md ./packages/text-vide/README.md &&
          cd ./packages/text-vide &&
          npm publish --tag oidc

      - name: Print npm debug log on failure
        if: failure()
        run: |
          LOG=$(ls -t /home/runner/.npm/_logs/*-debug-0.log 2>/dev/null | head -n1 || true)
          test -f "$LOG" && { echo "== NPM DEBUG LOG =="; cat "$LOG"; } || echo "no npm debug log"
