name: publish

on:
  release:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4.2.0
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: npm i -g npm@latest
      - run: pnpm install --frozen-lockfile

      - run: pnpm run lint
      - run: pnpm run test
      - run: pnpm run build

      - run: |
          cp ./README.md ./packages/text-vide/README.md &&
          cd ./packages/text-vide &&
          npm publish
